django/redes/domains/urls.py
from django.conf.urls import url
from . import views

app_name = 'domains'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^domains/$', views.dominios, name='dominios'),
    url(r'^new_domain/$', views.createDominio, name='create_domain'),
]

django/redes/redes/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from domains import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    # url(r'^special/', views.special, name='special'),
    url(r'^domains/', include('domains.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

django/redes/domains/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class domainUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    domain = models.TextField(max_length=10, blank=False)
    desciprion = models.TextField(blank=True)
    domain_user = models.TextField(max_length=8, blank=False)
    passwrd = models.TextField(max_length=10)
    created_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.domain

django/redes/domains/forms.py
from django import forms
from .models import UserProfileInfo, domainUser
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'password', 'email')


class DomainForm(forms.ModelForm):
    domain = forms.CharField(max_length=10, label='Dominio')
    desciprion = forms.CharField(label='descripcion')
    domain_user = forms.CharField(max_length=8, label='Usuario')
    passwrd = forms.CharField(
        widget=forms.PasswordInput(), max_length=10, label='contraseña')

    class Meta():
        model = domainUser
        exclude = ('user',)

django/redes/domains/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import UserForm, DomainForm
from .models import domainUser
from django.template import RequestContext
from django.shortcuts import render
from .llamadaScript import main

def index(request):
    return render(request, 'domains/index.html')


@login_required
def special(request):
    return HttpResponse("Ha inicidado sesión !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def createDominio(request):
    created = False
    if request.method == 'POST':
        domain_form = DomainForm(data=request.POST)
        if domain_form.is_valid():
            domain = domain_form.save(commit=False)
            domain.user = request.user
            domain.save()
            created = True
            # print(domain.domain, domain.domain_user, domain.passwrd, domain.user)
            # TODO Call script domain.domain, domain.domain_user, domain.passwrd, domain.user
            main(str(domain.user), str(domain.passwrd),str(domain.domain),str(domain.domain_user))
        else:
            print(domain_form.errors)
    else:
        domain_form = DomainForm()
    return render(request, 'domains/domain.html', {'domain_form': domain_form, 'created': created})


@login_required
def dominios(request):
    domains_list = domainUser.objects.filter(user=request.user)

    context_dict = {'domains': domains_list}

    return render(request, 'domains/my_domains.html', context_dict)


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
    return render(request, 'domains/registro.html',
                  {'user_form': user_form, 'registered': registered})

# Create your views here.


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(
                username, password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'domains/login.html', {})

django/redes/domains/templates/domains/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %}{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous" />
  <link rel="stylesheet" href={% static 'domains/styles.css' %} />
  <link href='https://fonts.googleapis.com/css?family=Audiowide' rel='stylesheet'>
</head>

<body>
  <section>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'index' %}" style="font-weight: bold;">Dominios</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'domains:dominios' %}">Dominios</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'domains:user_login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'domains:register' %}">Registro</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </section>
 

  {% block bodyblock %}{% endblock %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>

    <footer>
      <div  style="background-color: #343a40!important;">
        <nav style="height: 100px; color: #a5a5a5;font-weight:bolder">
          Pagina dominios
        </nav>
      </div>
      
        </footer>
      
      
</body>

</html>

django/redes/domains/templates/domains/domain.html
{% extends "domains/base.html" %} {% load static %} {% block bodyblock %}
<div class="container-login">
  <div class="container container-login" style="text-aling: center">
    {% if created %}
    <h1>Dominio creado!</h1>
    {% else %}
    <h1>Nuevo Dominio</h1>
    <h3>llene el formulario</h3>
    <form
      class="form-container"
      style="text=align: center"
      enctype="multipart/form-data"
      method="POST"
    >
      {% csrf_token %} {{ domain_form.as_p }}
      <div style="text-align: center">
        <input
          class="login-btn btn btn-primary"
          type="submit"
          name=""
          value="Crear Dominio"
        />
      </div>
    </form>

    {% endif %}
  </div>
</div>
{% endblock %}

django/redes/domains/templates/domains/index.html
{% extends "domains/base.html" %} {% block title %} Inicio | Dominios
{%endblock%} {% block bodyblock %}
<div class="container-login">
  <div class="container">
    {% if user.is_authenticated %}
    <h1 style="font-family: 'Audiowide';">Hola! &nbsp;{{ user.username }}</h1>
    {% else %}
    <h2 style="font-family: 'Audiowide';">Por favor inicie sesión ó registrese</h2>
    {% endif %}
  </div>
</div>
<div style="color:e8e8e8; background-color: #e8e8e8; margin-bottom: -12px;">
  <pre>



  </pre>
  <div>
    <pre>


    
    </pre>
    <div>
      <div>
        <pre>


    
        </pre>
      </div>
      <pre  >


    
      </pre>
    </div>
  </div>
</div>
{% endblock %}

django/redes/domains/templates/domains/login.html
{% extends 'domains/base.html' %}{% block bodyblock %}
<section class="container-login">
  <div class="container">
    <h1 style="font-family: 'Audiowide'; text-align: center;">INICIO DE SESION</h1>
    <div class="row justify-content-center">
      <div class="container-login col-6">
        <form method="post" action="{% url 'domains:user_login' %}">
          {% csrf_token %} {# A more "HTML" way of creating the login form#}
          <div class="form-group">
            <label for="username">Usuario:</label><br>
            <input type="text" class="form-control" name="username" aria-describedby="emailHelp" </div><br>
            <div class="form-group">
              <label for="password">Constrseña</label>
              <input type="password" class="form-control" name="password" />
            </div><br>
            <div style="text-align: center">
              <button type="submit" class="btn btn-outline-primary" style="width: 200px;">
                Login
              </button>
            </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock bodyblock %}

django/redes/domains/templates/domains/my_domains.html
{% extends "domains/base.html" %} {% load static %} {% block bodyblock %}
<div class="container-login">
  <div class="container container-login" style="text-aling: center">
    <h1 style="font-family: 'Audiowide';">Sus Dominios</h1><br><br><br>
    {% if domains %}
    <!-- <a href="{% url 'domains:create_domain' %}" >Crear un Dominio</a><br><br> -->
    <button type="button" class="btn btn-outline-dark"  
    onclick="location.href='{% url 'domains:create_domain' %}'">
    Crear un Dominio</button><br><br><br>
    <div class="container">
    <table class="table" style="border-style: solid;">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Dominio</th>
          <th scope="col">Descripcion</th>
          <th scope="col">Usuario</th>
          <th scope="col">Contraseña</th>
        </tr>
      </thead>
      <tbody>
        {% for domain in domains %}
        <tr>
          <td>{{ domain.domain }}</td>
          <td>{{ domain.desciprion }}</td>
          <td>{{ domain.domain_user }}</td>
          <td>{{ domain.passwrd }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

    {% else %}
    <h1>No hay dominios registrados!</h1>
    <a href="{% url 'domains:create_domain' %}">Crear un Dominio</a>
    {% endif %}
  </div>
</div>
{% endblock %}

django/redes/domains/templates/domains/registro.html
{% extends "domains/base.html" %} {% load static %} {% block bodyblock %}
<div class="container-login">
  <div class="container container-login" style="text-aling: center">
    {% if registered %}
    <h1 style="font-family: 'Audiowide';">Gracias por registrarse!</h1>
    {% else %}
    <h1 style="font-family: 'Audiowide';">Registro</h1><br>
    <h4>Llene el formulario</h4><br>
    <form 
      class="form-container"
      style="text=align: center"
      enctype="multipart/form-data"
      method="POST"
    >
      {% csrf_token %} {{ user_form.as_p }}
      <div style="text-align: center">
        <input
          class="login-btn btn btn-primary "
          type="submit"
          name=""
          value="Registrarse"
          style="width: 200px;"
        />
      </div>
    </form>

    {% endif %}
  </div>
</div>
{% endblock %}